{{- if and (.Values.redis) (.Values.redis.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/redis
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        redis:
        {{- toYaml .Values.redis | nindent 10 }}
      parameters:
        - name: redis.replica.replicaCount
          {{ if .Values.redis.replicaCount }}
          value: {{ .Values.redis.replicaCount | toString }}
          {{ else }}
          value: "1"
          {{ end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
